In [25]:
import pandas as pd
import numpy as np

In [26]:
df=pd.read_csv('data/StudentsPerformance.csv')
df

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
...,...,...,...,...,...,...,...,...
995,female,group E,master's degree,standard,completed,88,99,95
996,male,group C,high school,free/reduced,none,62,55,55
997,female,group C,high school,free/reduced,completed,59,71,65
998,female,group D,some college,standard,completed,68,78,77
999,female,group D,some college,free/reduced,none,77,86,86

In [27]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   str
 1   race/ethnicity               1000 non-null   str
 2   parental level of education  1000 non-null   str
 3   lunch                        1000 non-null   str
 4   test preparation course      1000 non-null   str
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), str(5)
memory usage: 62.6 KB

In [28]:
df.isnull().sum()/len(df)

gender                         0.0
race/ethnicity                 0.0
parental level of education    0.0
lunch                          0.0
test preparation course        0.0
math score                     0.0
reading score                  0.0
writing score                  0.0
dtype: float64

In [29]:
df=df.rename(columns={'race/ethnicity':'group','parental level of education':'parents_edu','test preparation course':'course','math score':'maths','reading score':'reading','writing score':'writing'})

In [30]:
df['gender']=df['gender'].map({'female':1,'male':0})
df['group']=df['group'].map({'group A':1,'group B':2,'group C':3,'group D':4,'group E':5})
df['course']=df['course'].map({'completed':1,'none':0})

In [31]:
df['percentage']=(df['maths']+df['reading']+df['writing'])/3
df

,gender,group,parents_edu,lunch,course,maths,reading,writing,percentage
0,1,2,bachelor's degree,standard,0,72,72,74,72.666667
1,1,3,some college,standard,1,69,90,88,82.333333
2,1,2,master's degree,standard,0,90,95,93,92.666667
3,0,1,associate's degree,free/reduced,0,47,57,44,49.333333
4,0,3,some college,standard,0,76,78,75,76.333333
...,...,...,...,...,...,...,...,...,...
995,1,5,master's degree,standard,1,88,99,95,94.000000
996,0,3,high school,free/reduced,0,62,55,55,57.333333
997,1,3,high school,free/reduced,1,59,71,65,65.000000
998,1,4,some college,standard,1,68,78,77,74.333333
999,1,4,some college,free/reduced,0,77,86,86,83.000000

In [32]:
female_above_85=((df['gender']==1) & (df['percentage']>85)).sum()/(df['gender']==1).sum()*100
male_above_85=((df['gender']==0) & (df['percentage']>85)).sum()/(df['gender']==0).sum()*100
print(f'''percentage of female student in first class:{female_above_85}
percentage of male student in first class:{male_above_85}''')

percentage of female student in first class:14.478764478764477
percentage of male student in first class:7.676348547717843

In [33]:
female_passed=((df['gender']==1) & (df['percentage']>40)).sum()/(df['gender']==1).sum()*100
male_passed=((df['gender']==0) & (df['percentage']>40)).sum()/(df['gender']==0).sum()*100
print(f'''percentage of female students passed:{female_passed}
percentage of male student passed:{male_passed}''')

percentage of female students passed:96.71814671814671
percentage of male student passed:96.88796680497926

In [34]:
course_student_percentage=((df['course']==1) & (df['percentage']>40)).sum()/(df['course']==1).sum()*100
noncourse_student_percentage=((df['course']==0) & (df['percentage']>40)).sum()/(df['course']==0).sum()*100
print(f'''possibility of passing for students completing test preperation course:{course_student_percentage}
possibility of passing for students not doing test preperation course:{noncourse_student_percentage}
hence,''')
if course_student_percentage>noncourse_student_percentage:
    print("possibility of passing for students completing test preperation course is more than others")
else:
    print("possibility of passing for students not doing test preperation course is more than ones who completed")

possibility of passing for students completing test preperation course:99.16201117318437
possibility of passing for students not doing test preperation course:95.48286604361371
hence,
possibility of passing for students completing test preperation course is more than others

In [35]:
course_student_topper_percentage=((df['course']==1) & (df['percentage']>85)).sum()/(df['course']==1).sum()*100
noncourse_student_topper_percentage=((df['course']==0) & (df['percentage']>85)).sum()/(df['course']==0).sum()*100
print(f'''possibility of being topper for students completing test preperation course:{course_student_topper_percentage}
possibility of being topper for students not doing test preperation course:{noncourse_student_topper_percentage}
hence,''')
if course_student_topper_percentage>noncourse_student_topper_percentage:
    print("possibility of being topper for students completing test preperation course is more than others")
else:
    print("possibility of being topper for students not doing test preperation course is more than ones who completed")

possibility of being topper for students completing test preperation course:17.59776536312849
possibility of being topper for students not doing test preperation course:7.632398753894081
hence,
possibility of being topper for students completing test preperation course is more than others

In [36]:
edu_order = {
    'some high school': 1,
    'high school': 2,
    'some college': 3,
    "associate's degree": 4,
    "bachelor's degree": 5,
    "master's degree": 6
}
df['parents_edu_level'] = df['parents_edu'].map(edu_order)

In [37]:
def classify_edu(edu):
    if edu in ['some high school', 'high school']:
        return 'low'
    elif edu in ['some college', "associate's degree"]:
        return 'medium'
    else:
        return 'high'

df['edu_category'] = df['parents_edu'].apply(classify_edu)

In [38]:
df.groupby('edu_category')['percentage'].mean()

edu_category
high      72.482109
low       64.056889
medium    69.017857
Name: percentage, dtype: float64

In [41]:
family_inc={
    'standard':'high',
    'free/reduced':'low'}
df['family_income']=df['lunch'].map(family_inc)

In [42]:
df.groupby('family_income')['percentage'].mean()

family_income
high    70.837209
low     62.199061
Name: percentage, dtype: float64